# Log File Path
log_path=logs/app_exit.log

# Log Format
log_format=txt

# Frequency For HeartBeat Workers (Only Integers)
period_ms=1500.3

# Flush Buffer
flush_log=1

# Number of ADD Workers
NB_WORKER_ADD=5

